<style type="text/css">
h1.title {
  font-size: 26px;
}
</style>
</br>

###Projects###

#### [HealthyU](http://rpubs.com/caitlinbrow/healthyU)  

- An ongoing, longitudinal study of individuals at risk for developing mood and anxiety disorders.
- See [here](http://rpubs.com/caitlinbrow/RNT) for the analyses included in a publication under review.
<br/>

#### [Differential Item Functioning](http://rpubs.com/caitlinbrow/DIF)

- Do the items of the Hoarding Rating Scale exhibit bias when measured in English vs. Spanish?

#### [Linking EMA and the P-Factor Model](http://rpubs.com/caitlinbrow/structuralregsEMA)

- How can momentary affective dynamics, measured using in-the-moment smartphone assessments, inform our understanding of the latent structure of psychopathology?

#### [Genetics](http://rpubs.com/caitlinbrow/genes)

- Genetic risk factors interact with early life stress to predict hoarding symptoms.

#### [Bifactor](http://rpubs.com/caitlinbrow/439858)

- Bifactor models represent a useful tool for parsing general versus specific variance in a construct.
